# Generated by Django 5.2.4 on 2025-07-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_alter_student_exam_hall_alter_student_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
